# Site settings
title: SugarBombEngine
email: #your-email@domain.com
url: "/"
baseurl: "/."
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: SugarBombEngine Dev Team

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
    #url: https://twitter.com/SBootstrap
  #- title: facebook
    #url:
  #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
    #url: http://bitbucket.org/jekyll
  - title: gitlab
    url: https://gitlab.com/BlackPhrase/sugarbombengine
  - title: github
    url: https://github.com/BlackPhrase/sugarbombengine

# Build settings
markdown: kramdown
permalink: pretty
