name: Build Project

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      - name: Clone iniparser
        run: |
          if [ ! -d "libs/iniparser" ]; then
            git clone https://github.com/ndevilla/iniparser.git libs/iniparser
          fi
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
